### ISSUE TITLE
Question regarding completeness of this example

### ISSUE THREAD

**Issue by jannikbuschke** [Urmade/TeamsTabSSO#1]
Hi Tobias,

If I am correct, this example shows the initial auth trigger and the backend receiving a token. Typically the next steps would be to cache the token in the backend and link it to the current session (i.e. via a cookie) or?

**Comment by urmade** [comment]
Hi Jannik,
exactly, this implementation focuses on showing the core concepts. For this to be used in production, it should at least be added:
- Token caching (You can use MSAL for this)
- Environment variables (Right now all settings / secrets have to be hard-coded in index.ts)
- Advanced token acquisition (Right now no error checks, MSAL takes care of this too)

Also, this example currently doesn't have a mechanism for receiving tokens with additional scopes. If you need to make MS Graph queries in Teams, you would have to implement a fallback popup auth flow in the frontend and alter the backend.
If the backend would query for a token with a scope it hasn't been granted, then an error would be returned to the backend. The backend then has to tell the frontend [the Teams tab] to launch a popup auth flow where it asks for consent of the user, and then retriggers the token acquisition process.

**Comment by jannikbuschke** [comment]
Thanks for clarifying.

One further question: The backend part is just the on behalf flow, so this part would also work in a non-Teams context right?
In a pure web context the difference would be how I trigger the redirect: inside Teams I use the js teams sdk (inside a popup if Im not mistaken), and in a normal web application I would do the redirect differently (maybe by just handcrafting the url).

**Comment by urmade** [comment]
The whole login flow (frontend and backend together) represent the [On-behalf-of flow.](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow#use-the-access-token-to-access-the-secured-resource). You could take the backend part for every other platform as well that implements On-behalf-of, basically you only have to pass it some token (that was created for your app, hence "On behalf of") to make the backend work.

If you would use this flow in a pure web app, you would have to alter the token acquisition process (instead of using the Teams SDK, there must be some other way to provide you the initial token). If you are developing a basic web app that should log the user in and acquire an access_token, the On-behalf-of flow isn't necessarily the right choice though. You could use the [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) (as implemented [here](https://github.com/Urmade/AzureActiveDirectoryNodeJSLogin) in a very simple way) as this is way more secure and easier to build / maintain. 
You would need a pretty specific use case to use an on-behalf-of flow for your own app (like for example you have a platform that allows integration of third parties and wants to pipe already existing integration into an iframe).

**Comment by urmade** [comment]
Closing issue as question seems to be answered

**Comment by jannikbuschke** [comment]
yes, thanks
